### ISSUE TITLE
feedback page

### ISSUE THREAD

**Issue by macguirerintoul** [mrintoul/iat-339-project-two#10]

**Comment by stuible** [comment]
Will this page we linked from the main nav?

**Comment by macguirerintoul** [comment]
We could also combine the contact/feedback into one page/form, what do you think of that? Then we can link to it from the main nav.

**Comment by stuible** [comment]
Ya I think that makes sense.

**Comment by macguirerintoul** [comment]
added in bb097f78af079c78
