### ISSUE TITLE
updated style guide page including layouts

### ISSUE THREAD

**Issue by macguirerintoul** [mrintoul/iat-339-project-two#12]

**Comment by stuible** [comment]
**Exact Requirement:**
> Update and publish your style guide along with your website. Make sure it includes the addition of any changes made to the original guide, as well as any layouts or structures created since the beginning of P2

Not 100% sure what this means, does he want us to explain how our layout classes work (container, col-6, etc?)

**Comment by macguirerintoul** [comment]
Yeah and probably show them, e.g. [Skeleton](http://getskeleton.com/#grid)

**Comment by stuible** [comment]
I love re-inventing the wheel!

**Comment by stuible** [comment]
Pretty much done just leaving open to remind myself to polish up the copy of this section

**Comment by stuible** [comment]
Finished as of f3edd7d00de570eb8fca328c105fa8630a3d1071
