### ISSUE TITLE
header logo should link to home page

### ISSUE THREAD

**Issue by macguirerintoul** [mrintoul/iat-339-project-two#20]
while we're here, is the box supposed to be cutting through the text @stuible?

**Comment by stuible** [comment]
It is.  I've experimented with it not doing that too and I don't know which I like more.

**Comment by macguirerintoul** [comment]
I feel like they might see it as an error or we couldn't figure out how to make the box big enough to hold the logo

**Comment by stuible** [comment]
Logo is now a link to home page as of f556b8299a33db525faf34be01d778648ac9c2fc .  In regards to the logo design I really hope he knows that we're competent enough to do that but I fear the same.
