### ISSUE TITLE
ensure all pages can be navigated via screen reader

### ISSUE THREAD

**Issue by macguirerintoul** [mrintoul/iat-339-project-two#24]
we can test using Apple VoiceOver, [ChromeVox](https://chrome.google.com/webstore/detail/chromevox/kgejglhpjiefppelpmljglcjbhoiplfn?hl=en) or [HaTeMiLe](https://addons.mozilla.org/en-US/firefox/addon/hatemile-for-browser/?src=search) for our Mozilla fanboys

**Comment by stuible** [comment]
Will do this tommorrow.

**Comment by macguirerintoul** [comment]
tested with ChromeVox, seems pretty good
