### ISSUE TITLE
card type cannot be selected using tab

### ISSUE THREAD

**Issue by macguirerintoul** [mrintoul/iat-339-project-two#25]
when tabbing through the checkout form, the card type cannot be selected. we could just automatically detect it using something like https://github.com/braintree/credit-card-type

**Comment by stuible** [comment]
Agreed, will implement this now.

**Comment by stuible** [comment]
I don't think the extra effort of implementing this library will really be appreciated so I'm just going to have it look as if one was automatically selected.

**Comment by stuible** [comment]
Removed radio buttons, emulated the look of an auto detecting credit card field.
