### ISSUE TITLE
add descriptions for products on details page

### ISSUE THREAD

**Issue by macguirerintoul** [mrintoul/iat-339-project-two#33]

**Comment by stuible** [comment]
Added description in 650102e5febdbfe128951ab64ebb86ab1f6af770 but still need to style it and add price + add to cart button.

**Comment by macguirerintoul** [comment]
content should be real btw, i think i saw lorem ipsum

**Comment by stuible** [comment]
Content is real as of: 6909b071006e578dd35b7cafdd5ec00d5fde2dfd
