### ISSUE TITLE
product details page

### ISSUE THREAD

**Issue by macguirerintoul** [mrintoul/iat-339-project-two#7]

**Comment by stuible** [comment]
Any way we can keen this feature and dynamically create the detail pages for all our product listings?

**Comment by macguirerintoul** [comment]
I don't know enough about web components yet, but if we can pass props via a link then we could create an `<m-product-details>` component and just pass it the info it needs from every product?

**Comment by stuible** [comment]
I think we'd need to make some kind of pseudo-router for that page where we get the hash navigation param and load in the correct product via json.

**Comment by stuible** [comment]
Created a page that uses URL params to display some of the stuff we need.  More work is needed on the page

**Comment by macguirerintoul** [comment]
Lol we don't need to do this, they can just be hard coded

**Comment by stuible** [comment]
Pretty much done, just a few style-things to polish up
