### ISSUE TITLE
header component

### ISSUE THREAD

**Issue by macguirerintoul** [mrintoul/iat-339-project-two#8]

**Comment by stuible** [comment]
Any specific functionality we need from this component?  If not I think it's done for now.

**Comment by macguirerintoul** [comment]
It looks like the nav is in there too, so as long as we keep that updated then we're good

**Comment by stuible** [comment]
Ya since Nav is pretty much a base element, I didn't create a webcomponent for it because it's redundant.  I nested the nav inside the header but we'll probably want to style the site nav and the styleguide page nav differently eventually.
